### ISSUE TITLE
Unreadable output

### ISSUE THREAD

**Issue by binarytrails** [binarytrails/xprobe2#1]
It seems xprobe2-0.3 (last version before discontinued) output has reported issues [1]. Below is the stdout from my Arch Linux [2]. Same is present on recent Linux distributions both in stdout and XML outputs.
```
[+] Primary guess:
[+] Host 192.168.1.3 Running OS: �b���U (Guess probability: 100%)
[+] Other guesses:
[+] Host 192.168.1.3 Running OS: 0?���U (Guess probability: 91%)
[+] Host 192.168.1.3 Running OS: 0?���U (Guess probability: 91%)
[+] Host 192.168.1.3 Running OS: P����U (Guess probability: 91%)
[+] Host 192.168.1.3 Running OS: P����U (Guess probability: 91%)
[+] Host 192.168.1.3 Running OS: �b���U (Guess probability: 91%)
[+] Host 192.168.1.3 Running OS: 0?���U (Guess probability: 91%)
[+] Host 192.168.1.3 Running OS: 0?���U (Guess probability: 91%)
[+] Host 192.168.1.3 Running OS: 0?���U (Guess probability: 91%)
[+] Host 192.168.1.3 Running OS: 0?���U (Guess probability: 91%)
[+] Cleaning up scan engine
[+] Modules deinitialized
[+] Execution completed.
```
[1] https://www.linuxquestions.org/questions/linux-newbie-8/unreadable-output-from-xprobe2-on-ubuntu-kali-4175630429/
[2] https://aur.archlinux.org/packages/xprobe2/#comment-730631

**Comment by fengxia41103** [comment]
Any update? I'm seeing the same on Ubuntu 20.04 Bionic

Xprobe2 v.0.3 Copyright (c) 2002-2005 fyodor@o0o.nu, ofir@sys-security.com, meder@o0o.nu

**Comment by binarytrails** [comment]
@fengxia41103  no.. i made this repo to track this issue to patch this eventually (me or someone else)!

An interesting finding is that if you rollback far enough in first Kali Linux version right after Backtrack era, it works! so this supports the theory that there is an outdated dependency in the font engine somewhere which should be not too complex to fix.

**Comment by fengxia41103** [comment]
Thanks for the quick response. I'll try the older version then.

**Comment by binarytrails** [comment]
@fengxia41103  no problem! my point is that it's not necessarily an older version since this tool has been removed from the original website. I had to dig into archive.org for my research to find the original paper and the source code which means that on older linux distribution it may be the same version but different dependencies version because this is how most of the software on Linux is inter-dependant!

**Comment by drew-coder** [comment]
Hello @binarytrails  where can I find an old version of xprobe in case I wished for a copy?

**Comment by binarytrails** [comment]
@drew-coder i think the idea is to fix the latest greatest since they don't develop it anymore to have the latest features.

some of the files are here:
- https://sourceforge.net/projects/xprobe/files/xprobe2/
- http://xprobe.sourceforge.net/oldindex.html

**Comment by drew-coder** [comment]
I really appreciate this 😊 💯 help. Thanks a lot once again 😊

**Comment by dschwen** [comment]
The garbled output is due to a trivial coding error. The method `const char *osid2char(int id)` returns a pointer to a temporary string that gets destroyed as soon as the method returns. It's an easy fix. I'll make a PR to this repo.

**Comment by binarytrails** [comment]
@dschwen works great! thank you for your contribution. I posted a detailed log of how to compile and run on kali linux at #2.
